name: PHPUnit 5.6
description: Run your PHPUnit tests with php 5.6 in your Github Actions.
inputs:
  coverage_html:
    description: Generate code coverage report in HTML format
    required: false

  coverage_text:
    description: Generate code coverage report in text format (true to output to console, path to output to file)
    required: false

  coverage_xml:
    description: Generate code coverage report in PHPUnit XML format
    required: false

  args:
    description: Extra arguments to pass to the phpunit binary
    required: false
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo "${{ github.action_path }}"
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash